#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate signed-off-by lines.

test "" = "$(grep '^signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate signed-off-by lines.
	exit 1
}

# Check for semantic commit message.

pattern='(bump|chore|configure|document|feature|fix|license|localize|make|no-make|optimize|refactor|revert|style|test)(\(\w{0,15}\))?(\[(#[1-9][0-9]*)?(@[1-9][0-9]*)?\])?(: \S.*)'
test "" = "$(grep -qE '$pattern' <<<"$1")" || {
	echo >&2 Invalid semantic commit message.
	exit 1
}